steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/gkhd_web:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'gkhd_web:base',
    '-t', 'gcr.io/$PROJECT_ID/gkhd_web:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/gkhd_web:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gkhd_web:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/gkhd_web:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/gkhd_web:latest',
    '.'
  ]
images: ['gcr.io/$PROJECT_ID/gkhd_web:base', 'gcr.io/$PROJECT_ID/gkhd_web:latest']

# Citations: UPE Tutoring, https://cloud.google.com/cloud-build/docs/build-config
# Fixed some stuff
